### ISSUE TITLE
He3 中的代码编辑器应该提供折行显示能力

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#16]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **zhenweiwang1990** February 23, 2023</sup>
方便查看一些单行内容非常长的场景，例如超长的 URL，压缩的 JSON，超长的日志等场景。</div>

**Comment by hongchaodeng** [comment]
cc @cs-storm @zhenweiwang1990

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，该问题已经反馈给产品部门，优先级为P2，请留意 issues 进度。

**Comment by EvilMoOd** [comment]
感谢您的反馈，针对文字换行问题，我们在新版He3中对代码编辑器进行一轮增强，您可以通过底部栏左侧换行icon进行换行
![image](https://user-images.githubusercontent.com/98245255/232362268-dbff0e77-7744-457d-8033-c91845ec5393.png)

您可以通过点击该短链接快速体验 https://t.he3app.com?hk1s
