### ISSUE TITLE
[Bug] JSON格式化时对于较大的整数会因为JSON的类型处理而丢失精度

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#23]

**Comment by fjiabinc** [comment]
如题,json格式化时,给的json字符串很大很长,工具使用效率大幅降低.处理速度慢

**Comment by hongchaodeng** [comment]
@fjiabinc 你好，感谢你的反馈！我另外开了一个 issue 来记录你说的问题：https://github.com/he3-app/he3-feedback/issues/72

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by Mashirowww** [comment]
让您久等了！问题已解决，可以前往最新的工具中体验～
link：https://t.he3app.com?5p3h
![image](https://user-images.githubusercontent.com/106071315/230816292-9a043a0e-9ec0-49fa-928f-bf54cd13c4a4.png)
