### ISSUE TITLE
json xml format save as file default ext is txt, please change thanks

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#29]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **lx19990999** March  3, 2023</sup>
please change it save as "*.json", "*.xml", thank you</div>

**Comment by Mashirowww** [comment]
The problem has been solved, you can go to the latest version of the tool to experience
link：https://t.he3app.com?msfl
![image](https://user-images.githubusercontent.com/106071315/229676023-7a485644-4f08-4973-a756-894242704b85.png)
