### ISSUE TITLE
更改scoop的默认安装目录后,安装报错

### ISSUE THREAD

**Issue by lin0kin** [he3-app/he3-feedback#32]
- bug: ERROR Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'D:\Scoop\apps\he3\1.2.1\He3_windows_installer_x64_1.2.1.exe' with working directory 'C:\Users\Lin0kin'. 系统找不到指定的文件。"

**Comment by hongchaodeng** [comment]
麻烦您能给出更详细的步骤吗？怎么更改 Scoop 的默认安装目录的？安装命令是什么？这样可以方便我们重现

**Comment by lin0kin** [comment]
> 有报错的详细信息吗？

这是相关的截图：

![image](https://user-images.githubusercontent.com/30078096/223354283-b96a5065-8ee5-4995-b299-3352f97e5cf8.png)

**Comment by hongchaodeng** [comment]
@lin0kin 
看一下这个：https://blog.csdn.net/done1182818968/article/details/121574537

你装其他软件有遇到问题吗？

**Comment by lin0kin** [comment]
> @lin0kin 看一下这个：https://blog.csdn.net/done1182818968/article/details/121574537
> 
> 你装其他软件有遇到问题吗？

这是第一次遇见这个问题。

链接里就是翻译的官方文档，我本地环境就是没有建global的仓库。我补了global的仓库也是报这个bug。

要不要考虑提供一个bucket的地址？第三方的bucket基本没啥问题。

**Comment by hongchaodeng** [comment]
提供一个 bucket 地址是什么意思？
Scoop 内容都是开源的哈：https://github.com/he3-app/he3-scoop

**Comment by lin0kin** [comment]
> 提供一个 bucket 地址是什么意思？ Scoop 内容都是开源的哈：https://github.com/he3-app/he3-scoop

就比如说 [dorado](https://github.com/chawyehsu/dorado) 大佬的第三方库，添加到scoop的bucket里面就能直接使用 scoop install 安装dorado库里的包。我表达的可能不是很清楚，就是建议提供一个自己的bucket，通过这个bucket提供你们的软件

我觉得闭源软件提供scoop的安装方式，那提供一个独立的库可能好一点。

----

在虚拟机上试了一下，更改了安装位置之后就会报一样的错误

![image](https://user-images.githubusercontent.com/30078096/224525563-d77d68f1-72ad-4e52-bbbc-1f933a7d4874.png)

**Comment by hongchaodeng** [comment]
@lin0kin 你好。感谢你的反馈。
我们已经安排人手在解决这个问题了。争取下个版本发布前修复！

**Comment by lin0kin** [comment]
> @lin0kin 你好。感谢你的反馈。 我们已经安排人手在解决这个问题了。争取下个版本发布前修复！

多谢大佬，希望产品能够成功

**Comment by hongchaodeng** [comment]
Reopen.
Keep it open until we fix the problem :)

**Comment by hongchaodeng** [comment]
你好，这个问题我们招到 root cause 了：

<img width="794" alt="Snipaste_2023-03-20_12-08-37" src="https://user-images.githubusercontent.com/920884/226245033-e1baae6d-8ffb-49f2-9e1e-bf6f76edaa55.png">

这里我们应该使用 he3-app org. 我们迁移了 repo 但是没及时更新官网。这是我们的不足。非常抱歉。

请你再试一下，如果没有问题的话我们就 close 这个 issue.

**Comment by lin0kin** [comment]
> 你好，这个问题我们招到 root cause 了：
> 
> <img alt="Snipaste_2023-03-20_12-08-37" width="794" src="https://user-images.githubusercontent.com/920884/226245033-e1baae6d-8ffb-49f2-9e1e-bf6f76edaa55.png">
> 
> 这里我们应该使用 he3-app org. 我们迁移了 repo 但是没及时更新官网。这是我们的不足。非常抱歉。
> 
> 请你再试一下，如果没有问题的话我们就 close 这个 issue.
> 
> ```
> scoop install "https://raw.githubusercontent.com/he3-app/he3-scoop/main/he3.json
> ```

确实可以安装了，不过这只是使用scoop把安装包下载下来，最终是运行安装程序。请问方便提供解压包，以便直接安装到scoop的环境里面吗？
![image](https://user-images.githubusercontent.com/30078096/226944378-de642ff6-242e-4538-a550-c7b61c288dd6.png)

**Comment by hongchaodeng** [comment]
@lin0kin 目前没有，官方也不推荐哈。

**Comment by lin0kin** [comment]
> @lin0kin 目前没有，官方也不推荐哈。

好吧,祝越来越好
