### ISSUE TITLE
[来自微信群] SQL 格式化多出来的空格问题

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#35]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/34

<div type='discussions-op-text'>

<sup>Originally posted by **hongchaodeng** March  6, 2023</sup>
sql格式化时如果sql内包含了函数，格式化出来的内容会在函数的`(`前面加个空格，这就导致了数据库执行会报语法错误
![WechatIMG3093](https://user-images.githubusercontent.com/920884/223005940-4fc0f87b-faac-46de-97a1-ce0769fe1e3a.png)
![WechatIMG3094](https://user-images.githubusercontent.com/920884/223005948-ffa3c42d-6a0f-42d6-a877-afd510781260.png)
![WechatIMG3095](https://user-images.githubusercontent.com/920884/223005953-d9160701-30be-4de6-a392-2271bab0e406.png)
</div>

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by Mashirowww** [comment]
让您久等了，问题已解决！请前往最新的工具中进行体验
link：https://t.he3app.com?outu
![image](https://user-images.githubusercontent.com/106071315/230314710-8d17cc4d-f81a-4232-9289-dbfb3e32d936.png)
