### ISSUE TITLE
JWT解析器 payload  和 header 显示框 无法拉长

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#36]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **cuibty** March  6, 2023</sup>
![223027415-10a746d5-ab81-4dd0-8d84-d1301c9f3299](https://user-images.githubusercontent.com/920884/223044114-c9df1b87-2aa4-4c92-91be-55f1544daae5.png)

</div>

**Comment by zhenweiwang1990** [comment]
strengthen CodeResult Component

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by Mashirowww** [comment]
我们对这个输出框加了自适应，解决了您的需求。可以在最新版本的工具中体验下！
link：  https://t.he3app.com?ukle
![image](https://user-images.githubusercontent.com/106071315/229682483-95a230fc-8cfe-4446-a738-88eb47013813.png)
