### ISSUE TITLE
[来自Discourse] 希望增加多种类型uuid支持

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#38]
具体参考 Free utilities for developers: https://web.echoo.app/#/?tk=uuid-generator

![162c8ff55501a91552b2da98d4f6c80c47c75b53_2_1380x794](https://user-images.githubusercontent.com/920884/223344958-37924c8f-608c-460f-ab77-fa2518a7aeb0.png)

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by Mashirowww** [comment]
让您久等了！该工具已经增强，可以前往最新的工具中体验～
link：https://t.he3app.com?1exr
![image](https://user-images.githubusercontent.com/106071315/231035120-375a8ed0-1b64-4b74-9023-ca847a4d608c.png)
