### ISSUE TITLE
[来自Discourse] Html表格转md表格时会有双引号

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#39]
> 请问这个双引号有什么意义?可以去掉吗?

```
| h1   | h2   | h3   | 
|------|------|------| 
| "v1" | "v2" | "v3" | 
| "v4" | "v5" | "v6" | 
```

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by EvilMoOd** [comment]
您好，感谢您的反馈，针对您提出的问题我们在新版工具中进行了修复，新版HTML转换工具中去掉了多余的双引号
![image](https://user-images.githubusercontent.com/98245255/230853857-5d11b480-c555-4ef6-84ef-5d98e32f6c30.png)

您可以点击该链接体验新工具https://t.he3app.com?gvfe
