### ISSUE TITLE
[来自微信群] 在About这里加一个提交bug的方式

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#51]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **hongchaodeng** March 11, 2023</sup>
<img width="228" alt="Screenshot 2023-03-11 at 08 03 32" src="https://user-images.githubusercontent.com/920884/224460226-14da0daa-4f3f-40c9-8116-ae4783996606.png">
</div>

**Comment by zhenweiwang1990** [comment]
在最新版本里面已经可以方便在 About 这里提交工具相关的 feedback 了。
