### ISSUE TITLE
希望加一些SQL to any query的功能

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#53]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/52

<div type='discussions-op-text'>

<sup>Originally posted by **Nomango** March 13, 2023</sup>
比如 SQL to mongodb query，SQL to ES query 等等</div>

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！已经增加了SQL to JSON Query：https://t.he3app.com?hbde与SQL to MongoDB Query：https://t.he3app.com?8122
