### ISSUE TITLE
[来自微信群] UTC 转时间戳不工作

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#54]
V1.2.11 MAC 13.2.1 这里不管怎么改时间戳都不变，也不报错
另外希望支持2023-03-13 10:33:36 这种格式转时间戳

同时英文叫 "UTC Time to Unix" 应该改成 "UTC Time to Timestamp"

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by congcongnalian** [comment]
![image](https://user-images.githubusercontent.com/68501045/229760898-31f6205c-45b9-4042-8014-0c1d141165c9.png)
非常高兴您能提出反馈！该问题已修复，并且除了新增DateTime转时间戳，还新增了ISO8601， Date转时间戳。在使用时，请注意他们的格式： DateTime = 'YYYY-MM-DD HH:mm:ss',
  RFC2822 = 'ddd, DD MMM YYYY HH:mm:ss ZZ',
  ISO8601 = 'YYYY-MM-DDTHH:mm:ssZ',
  Date = 'YYYY-MM-DD'
点击最新链接查看：https://t.he3app.com?rpxy
