### ISSUE TITLE
SQL 格式化出错

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#59]
<img width="502" alt="WechatIMG3951" src="https://user-images.githubusercontent.com/920884/225551726-eed42c81-a760-44ea-95c3-9c3fa6adc5c8.png">

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈!该问题已修复，并且您可以使用模板#{name}或者{name},并且对特殊符号@,#,$也开放支持，您可以通过如下链接体验：https://t.he3app.com?outu
![image](https://user-images.githubusercontent.com/68501045/231097873-3712e9e6-6d15-4e0f-be36-9d9d9c8b3ce8.png)
![image](https://user-images.githubusercontent.com/68501045/231099056-49aa10fa-c243-49d4-be98-b7f4aa39c4f9.png)
