### ISSUE TITLE
[来自微信群] sql格式化，关键字没有统一成大写或小写

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#68]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/67

<div type='discussions-op-text'>

<sup>Originally posted by **hongchaodeng** March 17, 2023</sup>
没有统一成大写，看着别扭:

![WechatIMG3984](https://user-images.githubusercontent.com/920884/225946754-bf5cd4c3-60fa-4dcd-92bf-4cfcb19d17e4.jpeg)
</div>

**Comment by lyzhang1999** [comment]
p1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by congcongnalian** [comment]
![image](https://user-images.githubusercontent.com/68501045/229679773-9cc63de4-d259-4ff8-b981-cb9764be2c9f.png)
非常高兴你能提出反馈，该问题已修复，这是最新的链接：https://t.he3app.com?outu
