### ISSUE TITLE
圖片轉圖標的兩個問題

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#69]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/65

<div type='discussions-op-text'>

<sup>Originally posted by **alctny** March 17, 2023</sup>
功能：圖片轉圖標

問題：
1. 不勾選平台會生成空文件
2. 不輸入文件名默認生成的文件名會以`--`開頭，以 -- 開頭對命令行很不友好，且意義不明

希望解決方案：
1. 不勾選目標平台默認生成所有平台或進行提示
2. 默認文件名不要以 `--` 開頭
</div>

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by EvilMoOd** [comment]
你好，感谢您的反馈
1. 针对生成空文件的问题，我们做了消息提示以提供更好的体验
2. 针对默认文件名的问题，如果文件名输入框为空的情况下，我们提供`icon-`的前缀以及图片尺寸作为默认文件名
以上的修复你可以在最新版本体验到
点击进入该工具👉https://t.he3app.com?1ve2
