### ISSUE TITLE
密碼生成器可以生成詞組

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#70]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **alctny** March 16, 2023</sup>
希望密碼生成器可以生成單詞組合，如同 [1password generator](https://1password.com/password-generator/) 的 Memorable 模式。

這樣生成的密碼會更容易記憶以及輸入</div>

**Comment by lyzhang1999** [comment]
p1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by congcongnalian** [comment]
ready to start

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！1password generator 的 Memorable功能已经增加，并且还增加了PIN功能，点击最新链接查看：https://t.he3app.com?39jf
![image](https://user-images.githubusercontent.com/68501045/230882656-e755ccf0-7011-4d8b-b5f3-14363622becf.png)
![image](https://user-images.githubusercontent.com/68501045/230882695-1d9d04ac-8b25-4df3-b107-6e20d2462977.png)
