### ISSUE TITLE
[来自微信群] 提供字体大小调节选项

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#74]
目前在大屏幕下字体偏小。用户希望能够调节字体大小并且保存起来，这样下一次打开还是那个大小。

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by congcongnalian** [comment]
感谢您能提出反馈！该功能已经添加，在我们官网 https://he3.app/zh/ 下载最新版或升级您本地已有版本可以体验该功能。
![20230510102352_rec_](https://github.com/he3-app/he3-feedback/assets/68501045/4ef6f873-c73a-41e1-9b5f-633c3fd71b2c)
⚠️：使用 <kbd>cmd</kbd> + <kbd>+</kbd>/<kbd>-</kbd>一样可以实现缩放永久保存。
