### ISSUE TITLE
TSV 转 JSON，切分方式错误

### ISSUE THREAD

**Issue by zhangze-github** [he3-app/he3-feedback#75]
![img_v2_88bc8bfc-ebe0-4ae8-b2a8-fecfe4630c4g](https://user-images.githubusercontent.com/41512027/226275468-8287920e-4adf-44fc-a9da-36e89c80bd11.jpg)

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by EvilMoOd** [comment]
你好，针对您提出的三点意见已进行了以下修复
1. 针对TSV转换中出现的错误识别逗号情况进行了修复，现在可以正常通过tab制表符来进行建表
2. 针对tab键输入导致indent的问题进行了修复，现在在未选中文本的光标输入情况下，可以通过tab键进行制表符键入
3. 针对文件导出也进行了修复，现在可以正常导出相应转换后文件后缀

您可以通过该工具链接体验到新版工具https://t.he3app.com?pa0i
