### ISSUE TITLE
[来自微信群] 响应头的headers有重复的 Header 没有显示出来

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#80]
Chrome DevTool 里面会把所有重复的 Header 都显示出来，如图：

<img width="1436" alt="WechatIMG4083" src="https://user-images.githubusercontent.com/920884/226842334-5b1a5a34-4396-4861-ae80-999312f5daae.png">

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。
