### ISSUE TITLE
增强 He3的代码编辑器

### ISSUE THREAD

**Issue by hongchaodeng** [he3-app/he3-feedback#83]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/82

<div type='discussions-op-text'>

<sup>Originally posted by **winstones2** March 23, 2023</sup>
希望能增加一个根据窗口宽度自动换行的功能。
比如JSON格式化的场景里，如果原JSON很长且格式有错误，虽然he3有提示，其实很难找到格式错误的地方。</div>

**Comment by hongchaodeng** [comment]
内部之前讨论过，有更多通用的增强点想法：

增加设置 Panel，允许用户控制编辑器的若干显示选项，并增加一些常用操作。

1. 增加切换是否折行显示按钮(line wrapping); 
1. 增加复制，粘贴，撤销icon按钮; 
1. 支持 cmd + 左键点击打开 URL ; 
1. 支持设置Tab 缩进的空格数; 
1. 显示光标位置; 
1. 缩放字体大小。

https://codemirror.net/examples/panel/

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！上面功能已经增加，he3已经显著增强。可以自动更新体验，或者去he3官网下载最新安装包体验 : https://he3.app/zh/
